### ISSUE TITLE
Verify that bluetooth.config file is still read correctly following file reorganisation

### ISSUE THREAD

**Issue by ajewers** [yorkrobotlab/ardebug#13]
The source files have now been moved into folders, however the bluetooth.config file has remained in the root. Would be good if you could verify that it is still loaded correctly.

**Comment by charlottearndt** [comment]
The file is currently expected to be in the same folder as the executable. This means it has to be copied into another folder anyway. This is about to change once the functionalities to modify the config file and add devices via the ARDebug software is implemented. Then manual modification is not needed anymore.
